apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: virtualmachines-application-set-dr
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/rmallam/kubevirt-gitops.git
        revision: restructure
        directories:
          - path: "two-cluster-pattern/helm/**"
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: default
      source:
        helm:
          valueFiles:
          - values-dr.yaml
        repoURL: https://github.com/rmallam/kubevirt-gitops.git
        targetRevision: restructure
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}'
      syncPolicy:
        syncOptions:
          - Validate=true
          - CreateNamespace=true
