apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: virtualmachines-application-set
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/rmallam/kubevirt-gitops.git
        revision: restructure  # Changed from HEAD to specific branch name
        directories:
          - path: "two-cluster-pattern/helm/**"
  template:
    metadata:
      name: 'two-cluster-pattern-{{ path.basename }}'
    spec:
      project: two-cluster-dr
      source:
        helm:
          valueFiles:
          - values.yaml
        repoURL: https://github.com/rmallam/kubevirt-gitops.git
        targetRevision: restructure # Changed from HEAD to specific branch name
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}'
      syncPolicy:
        syncOptions:
          - Validate=true
          - CreateNamespace=true
