apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "virtualmachines.fullname" . }}-logs
  labels:
    app.kubernetes.io/name: {{ include "virtualmachines.fullname" . }}-logs
    app.kubernetes.io/part-of: python-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # If you have a specific StorageClass, uncomment and specify it
  # storageClassName: your-storage-class
  # If you want to bind to a specific existing PV, uncomment and specify it
    #volumeName: pvc-bd9573bd-f125-4143-87ad-d3048612f125
