{{- if eq .Values.access.ssh.enabled true }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "virtualmachines.fullname" . }}
data:
  key: {{ .Values.access.ssh.pubkey }}
type: Opaque
{{- end -}}