# Base resources for the stretchtest application
# This would contain all the common resources that were previously defined in the values-common.yaml Helm file
# For example:

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: stretchtest-vm
spec:
  running: true
  template:
    spec:
      domain:
        devices: {}
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      terminationGracePeriodSeconds: 0
---
# Include other common resources here
