# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: bootstrap-appset-simple
#   namespace: openshift-gitops
# spec:
#   generators:
#     - git:
#         repoURL: https://github.com/rmallam/gitops-openshift.git
#         revision: HEAD
#         directories:
#           {{- range .Values.apps }}
#           {{- if eq .enabled true }}
#           - path: {{ .name }}
#             recurse: {{ .recurse | default false }}
#             {{- if .exclude }}
#             exclude: {{ .exclude }}
#             {{- end }}
#           {{- end }}
#           {{- end }}
#   template:
#     metadata:
#       name: '{{ "{{" }}path.basename{{ "}}" }}'
#       finalizers:
#         - resources-finalizer.argocd.argoproj.io
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/rmallam/gitops-openshift.git
#         targetRevision: HEAD
#         path: '{{ "{{" }}path{{ "}}" }}'
#         directory:
#           recurse: false
#       destination:
#         name: in-cluster
#         # Just use path.basename as the namespace
#         namespace: '{{ "{{" }}path.basename{{ "}}" }}'
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true
#           allowEmpty: false
#         syncOptions:
#           - Validate=true
#           - CreateNamespace=true
#           - PrunePropagationPolicy=foreground
#           - PruneLast=true
