apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ include "virtualmachines.fullname" . }}
  name: {{ include "virtualmachines.fullname" . }}
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ include "virtualmachines.fullname" . }}
    weight: 100
  wildcardPolicy: None