apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "virtualmachines.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "virtualmachines.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "virtualmachines.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "virtualmachines.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "virtualmachines.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
