apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  namespace: your-application-namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi  # Arbitrary value as EFS is elastic
