apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: virtualmachines-application-set
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - name: logger
            values: values.yaml
            namespace: py-logger
          - name: logger
            values: values-dr.yaml
            namespace: py-logger
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        helm:
          valueFiles:
          - '{{values}}'
        repoURL: https://github.com/rmallam/kubevirt-gitops.git
        targetRevision: HEAD
        path: 'virtualmachines/rsyncapp'  # Path to your Helm chart
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - Validate=true
          - CreateNamespace=true
