apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: virtualmachines-application-set
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/rmallam/kubevirt-gitops.git
        revision: HEAD
        directories:
          - path: "virtualmachines/**"
          - exclude: "virtualmachines/stretchtest/**"
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: default
      source:
        helm:
          valueFiles:
          - values-dr.yaml
        repoURL: https://github.com/rmallam/kubevirt-gitops.git
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}'
      syncPolicy:
        syncOptions:
          - Validate=true
          - CreateNamespace=true
